/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	Home: [
		{
			type: 'doc',
			id: 'getting-started',
		},
		{
			type: 'doc',
			id: 'security',
		},
		{
			type: 'doc',
			id: 'flows',
		},
		{
			type: 'doc',
			id: 'for-ai-tools',
		},
	],
	// Guides sidebar removed — content kept on disk at docs/Guides/ but
	// not surfaced in nav until the section is ready to ship. To restore,
	// add the Guides block back here and the matching navbar item in
	// docusaurus.config.js.
	Client: [
		{
			type: 'html',
			value: '<h3>Client SDK</h3>',
			defaultStyle: true,
			className: 'sidebar-header'
		},
        {
			type: 'autogenerated',
			dirName: 'Client',
		}
	],
	Connector: [
		{
			type: 'html',
			value: '<h3>Self-Hosted WordPress Plugin</h3>',
			defaultStyle: true,
			className: 'sidebar-header'
		},
        {
			type: 'autogenerated',
			dirName: 'Connector'
		}
	],
	Account: [
		{
			type: 'html',
			value: '<h3>Account</h3>',
			defaultStyle: true,
			className: 'sidebar-header'
		},
        {
			type: 'autogenerated',
			dirName: 'Account'
		}
	],
};

module.exports = sidebars;
