/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	Home: [
		{
			type: 'doc',
			id: 'getting-started',
		},
		{
			type: 'doc',
			id: 'security',
		},
		{
			type: 'doc',
			id: 'flows',
		},
		{
			type: 'doc',
			id: 'for-ai-tools',
		},
	],
	// Guides moved into the Account section as Account/Guides/. They
	// surface automatically through Account's autogenerated sidebar.
	Connector: [
		{
			type: 'html',
			value: '<h3>Self-Hosted WordPress Plugin</h3>',
			defaultStyle: true,
			className: 'sidebar-header'
		},
        {
			type: 'autogenerated',
			dirName: 'Connector'
		}
	],
	Account: [
		{
			type: 'html',
			value: '<h3>Account</h3>',
			defaultStyle: true,
			className: 'sidebar-header'
		},
        {
			type: 'autogenerated',
			dirName: 'Account'
		}
	],
	// Developers section: Client SDK, Connector internals (hooks /
	// signing / secrets), and the HTTP API. The user-facing Connector
	// install + permissions docs stay in /Connector; only engineer-
	// audience material lives here.
	Developers: [
		{
			type: 'html',
			value: '<h3>Developers</h3>',
			defaultStyle: true,
			className: 'sidebar-header'
		},
		{
			type: 'autogenerated',
			dirName: 'Developers'
		}
	],
};

module.exports = sidebars;
